### PR TITLE
go 1.7beta2 -> go 1.7rc2, go 1.6.2 -> go 1.6.3, dropping go 1.4.2

### PR DESCRIPTION
**Pull request by jonlawlor**

### CODE REVIEW

**Comment by jonlawlor** [comment]
Seems like a change to goimports within the last month doesn't play well with go 1.4.2.  What is it being used for in internal's testing?

**Comment by kortschak** [comment]
Yes, it was. We check to make sure that go generate has been run on the asm package. Code generation depends on goimports.

There was a whole heap of work on goimports over the past few days. That probably broke it on 1.4. I don't know if @bradfitz knows about this breakage or whether it's a concern for the Go core devs. I don't have a huge problem with this - when 1.7 is released, we will be dropping 1.4 anyway.

**Comment by kortschak** [comment]
In the absence of objections from others, I would say we should drop go1.4 now. Unless someone else sends a CL to change the goimports dependencies or make them build tag aware, the situation is going to stay the same.

**Comment by jonlawlor** [comment]
I agree.  I'll change this branch and then wait for any objections.

**Comment by jonlawlor** [comment]
I filed an issue at golang/go#16444 - we'll see if they want to keep support for goimports prior to 1.5.

e: oops, didn't see that you already had one and it was closed.  I guess it is time to merge!

**Comment by kortschak** [comment]
Sorry, I should have mentioned it.

**Pull request merged**
