### PR TITLE
asm: avoid overflow in Dscal benchmarks

### PR DESCRIPTION
**Pull request by vladimir-ch**

### CODE REVIEW

**Comment by vladimir-ch** [comment]
PTAL @kortschak

**Comment by btracey** [comment]
LGTM

**Comment by kortschak** [comment]
Why does coveralls think this is a failure? There are no build failures and the test coverage didn't change.

LGTM

**Comment by vladimir-ch** [comment]
No idea. Maybe exactly because it didn't change? Look at that negative zero.

**Pull request merged**
