### PR TITLE
travis: update test matrix

### PR DESCRIPTION
**Pull request by kortschak**
go1.5.2 -> go1.5.3
go1.6beta2 -> go1.6rc1

### CODE REVIEW

**Comment by kortschak** [comment]
@jonlawlor Any idea why github interprets the coveralls result as a failure? There is no change and the builds were successful.

**Comment by jonlawlor** [comment]
I think it is failing because of the "-0.0%" decrease in coverage.  Digging a bit deeper it looks like coveralls will mark a test as failed if coverage decreases by too much, and I guess the default is 0%, so any decrease in coverage causes the test to fail.  Digging a bit deeper again, negative 0.0% is caused by a floating point issue on coveralls side.  The easiest way to fix is to set an amount of coverage that we are comfortable with losing, basically an epsilon.  It is kind of dumb on coveralls side, so I expect they'll address this eventually.

For now I'll set the "COVERAGE DECREASE THRESHOLD FOR FAILURE"  to 1%.

**Comment by jonlawlor** [comment]
After setting the threshold to 1% the test passed.  I'll set it for the other gonum packages as well.  Do you prefer a smaller % than 1%?

**Comment by kortschak** [comment]
1% is fine. Should we file an issue with coveralls?

**Comment by jonlawlor** [comment]
There already is one at https://github.com/lemurheavy/coveralls-public/issues/565

**Comment by kortschak** [comment]
Thanks for following that up. Dodgey decision on their part IMO.

**Comment by kortschak** [comment]
TBR @gonum/developers

**Pull request merged**
