### PR TITLE
internal/asm/...: remove outdated commments

### PR DESCRIPTION
**Pull request by kortschak**
Please take a look.

### CODE REVIEW

**Review by vladimir-ch — APPROVED** [review]
Strictly speaking, these comments are not outdated, but we don't have them for other functions, so it's ok remove them.

**Comment by kortschak** [comment]
They're outdated in that `uintptr` cannot be negative.

**Comment by vladimir-ch** [comment]
Ah, ok, those `uintptr`.

**Comment by kortschak** [comment]
Though strictly speaking, they are not outdated since we never used signed integers in these parameter positions. So "redundant" would have been better.

**Pull request merged**
