### PR TITLE
change DaxpyUnitary to take a destination parameter

### PR DESCRIPTION
**Pull request by fhs**

### CODE REVIEW

**Comment by kortschak** [comment]
I have a noasm build tag PR to send in a few minutes. This will allow you to easily check the performance impact of the Go implementation change. Would you wait until that's merged and do a benchmark on this?

**Comment by fhs** [comment]
ok, this PR can wait

**Comment by kortschak** [comment]
LGTM after benchmark.

**Comment by fhs** [comment]
benchmarks are in the commit message

**Comment by kortschak** [comment]
Thanks.

**Pull request merged**
